Repository elefan-grenoble/gestion-compte, pull requests merged in 2022-10, with the labels that each got.

#528 Fix the event proxy conditions and the signature sheet
  app/Resources/views/admin/event/signatures.html.twig
  app/Resources/views/default/event/proxy/give.html.twig
  src/AppBundle/Controller/EventController.php
Labels: Bug, Events and dynamic contents

#531 Créneau fixe : répare l'affichage du jour de la semaine
  src/AppBundle/Entity/Period.php
Labels: Bug, GUI/frontend

#532 Refactoring de l'affichage des créneaux
  app/Resources/views/booking/_partial/home_shift_card.html.twig
  app/Resources/views/booking/_partial/reserved_shift_card.html.twig
  app/Resources/views/user/_partial/mini_shift_card.html.twig
  app/Resources/views/user/_partial/period_position_card.html.twig
  app/Resources/views/user/_partial/shift_card.html.twig
  app/Resources/views/user/_partial/shift_card_header.html.twig
  app/Resources/views/user/_partial/shift_card_validation_status.html.twig
Labels: Enhancement, GUI/frontend

#536 Refactoring de l'affichage des créneaux
  app/Resources/views/booking/_partial/home_shift_card.html.twig
  app/Resources/views/booking/_partial/reserved_shift_card.html.twig
  app/Resources/views/user/_partial/mini_shift_card.html.twig
  app/Resources/views/user/_partial/period_position_card.html.twig
  app/Resources/views/user/_partial/shift_card.html.twig
  app/Resources/views/user/_partial/shift_card_header.html.twig
  app/Resources/views/user/_partial/shift_card_validation_status.html.twig
Labels: Enhancement, GUI/frontend

#533 Orienter les membres qui souhaitent geler leur compte
  app/Resources/views/Profile/show_content.html.twig
  app/Resources/views/member/_partial/frozen.html.twig
  app/Resources/views/member/show.html.twig
  app/config/config.yml
  app/config/parameters.yml.dist
Labels: Enhancement, Account and membership, GUI/frontend

#543 remove MaterializeCSS and JQuery legacy bundles and update composer.json
  app/AppKernel.php
  app/Resources/views/layout.html.twig
  app/Resources/views/layoutlight.html.twig
  app/config/config.yml
  composer.json
  composer.lock
  src/AppBundle/Resources/public/js/jquery-3.6.js
  src/AppBundle/Resources/public/js/jquery-3.6.min.js
Labels: Technical debt

#542 Rôles : permettre à un ROLE_ADMIN de supprimer un événement
  src/AppBundle/Controller/EventController.php
Labels: Security, Events and dynamic contents

#544 Admin : cleanup des templates des formations
  app/Resources/views/admin/formation/edit.html.twig
  app/Resources/views/admin/formation/list.html.twig
  app/Resources/views/admin/formation/new.html.twig
  src/AppBundle/Controller/FormationController.php
Labels: Account and membership, GUI/frontend

#547 Rôle : permettre à un ROLE_ADMIN de donner des rôles enfants
  app/Resources/views/member/_partial/recorded_registrations.html.twig
  app/Resources/views/member/_partial/roles.html.twig
  app/Resources/views/member/show.html.twig
  src/AppBundle/Controller/BookingController.php
  src/AppBundle/Controller/UserController.php
Labels: Security

#550 Admin : permettre à un n'importe quel ROLE_ADMIN_PANEL d'accéder à l'admin
  src/AppBundle/Controller/AdminController.php
Labels: Bug, Security

#504 Admin : page avec la liste des roles
  app/Resources/views/admin/index.html.twig
  app/Resources/views/admin/user/admin_list.html.twig
  app/Resources/views/admin/user/roles_list.html.twig
  app/config/config.yml
  src/AppBundle/Controller/AdminController.php
Labels: GUI/frontend, Security

#507 Admin : refactoring de ROLE_USER_VIEWER
  README.md
  app/Resources/views/admin/index.html.twig
  app/Resources/views/admin/pre_user/list.html.twig
  app/Resources/views/ambassador/phone/list.html.twig
  app/Resources/views/beneficiary/confirm.html.twig
  app/Resources/views/beneficiary/edit_beneficiary.html.twig
  app/Resources/views/beneficiary/find_member_number.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/default/tools/office_tools.html.twig
  app/Resources/views/member/add_beneficiary.html.twig
  app/Resources/views/member/new.html.twig
  app/Resources/views/member/show.html.twig
  app/Resources/views/registrations/list.html.twig
  app/Resources/views/user/edit_firewall.html.twig
  app/Resources/views/user/helloasso_resolve_orphan.html.twig
  app/Resources/views/user/quick_new.html.twig
  app/config/security.yml
  src/AppBundle/Controller/AdminController.php
  src/AppBundle/Controller/AmbassadorController.php
  src/AppBundle/Controller/DefaultController.php
  src/AppBundle/Controller/MembershipController.php
  src/AppBundle/Controller/NoteController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/EventListener/EmailingEventListener.php
Labels: GUI/frontend, Security
