Repository elefan-grenoble/gestion-compte, pull requests merged in 2023-04, with the labels that each got.

#804 Semaine type : répare l'url de submit du filtre sur la version anonyme
  src/AppBundle/Controller/PeriodController.php
Labels: Bug, Interface utilisateur, Semaine type et créneaux

#821 Événements : nouveau champ 'end'
  app/DoctrineMigrations/Version20230417102556_event_end.php
  app/Resources/views/admin/event/_partial/card.html.twig
  app/Resources/views/admin/event/edit.html.twig
  app/Resources/views/admin/event/list.html.twig
  app/Resources/views/admin/event/new.html.twig
  app/Resources/views/admin/membershipshiftexemption/edit.html.twig
  app/Resources/views/admin/user/import.html.twig
  app/Resources/views/beneficiary/find_member_number.html.twig
  app/Resources/views/user/tools/find_me.html.twig
  app/Resources/views/widget/generate.html.twig
  src/AppBundle/Entity/Event.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Form/SocialNetworkType.php
Labels: Interface utilisateur, Evénements et contenus dynamiques

#822 Événements : nouvelle entité pour définir des types d'événements
  app/DoctrineMigrations/Version20230417123838_event_kind_entity.php
  app/Resources/views/admin/event/kind/edit.html.twig
  app/Resources/views/admin/event/kind/list.html.twig
  app/Resources/views/admin/event/kind/new.html.twig
  app/Resources/views/admin/event/list.html.twig
  app/Resources/views/admin/index.html.twig
  src/AppBundle/Controller/EventController.php
  src/AppBundle/Controller/EventKindController.php
  src/AppBundle/Entity/EventKind.php
  src/AppBundle/Form/EventKindType.php
  src/AppBundle/Repository/EventKindRepository.php
Labels: Evénements et contenus dynamiques

#823 Événements : pouvoir définir le type d'événement
  app/DoctrineMigrations/Version20230417140110_event_kind.php
  app/Resources/views/admin/event/_partial/card.html.twig
  app/Resources/views/admin/event/edit.html.twig
  app/Resources/views/admin/event/kind/list.html.twig
  app/Resources/views/admin/event/list.html.twig
  app/Resources/views/admin/event/new.html.twig
  app/Resources/views/beneficiary/_partial/info.html.twig
  src/AppBundle/Entity/Event.php
  src/AppBundle/Entity/EventKind.php
  src/AppBundle/Form/EventType.php
  src/AppBundle/Repository/EventKindRepository.php
Labels: Evénements et contenus dynamiques

#808 Créneau fixe : afficher le nombre de créneaux effectués
  app/Resources/views/user/_partial/period_position_card.html.twig
  src/AppBundle/Entity/PeriodPosition.php
  src/AppBundle/Entity/Shift.php
  src/AppBundle/Repository/ShiftFreeLogRepository.php
  src/AppBundle/Repository/ShiftRepository.php
  src/AppBundle/Service/ShiftService.php
Labels: Comptes et adhésions, Interface utilisateur, Semaine type et créneaux

#827 E-mail de confirmation lors de la réservation d'un créneau
  app/Resources/views/emails/shift_booked_archive.html.twig
  app/Resources/views/emails/shift_booked_confirmation.html.twig
  app/Resources/views/emails/shift_reminder.html.twig
  src/AppBundle/Command/ShiftReminderCommand.php
  src/AppBundle/EventListener/EmailingEventListener.php
Labels: Amélioration, Semaine type et créneaux
